### ISSUE TITLE
"Get Help" link should be changed to Gitbook Docs

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/spark#1194]
The "Get Help" link in the `/about` page links to the BPM GitHub repo, I think we should change that to point to `https://processmaker.gitbook.io/processmaker-4-community/-LPblkrcFWowWJ6HZdhC/`

**Comment by milaendo** [comment]
@PMQABen The link you provided leads here 
![screen shot 2019-01-22 at 1 44 47 pm](https://user-images.githubusercontent.com/29641725/51567377-e5e6cf00-1e4b-11e9-836c-92104e82201b.png)

**Comment by PMQABen** [comment]
Yeaaaaah, I might need to loop Louis in on this one, because that URL is getting weird. If it gets opened directly in any browser, it loads just fine. If we try loading it via the /about page, it either throws "page not found" or it wants us to log into gitbook.
