### ISSUE TITLE
Script output does not extend the length of the content DIV

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/spark#1344]
1. Create a new script
```php
<?php
$principal = $data["principal"];
$interest = ($data["interest"]/100);
$time = $data["time"];

$days = 365;
$a = (1 + ($interest/365));
$b = ($days*$time);
$total=round($principal*(pow($a, $b)),2);

return [
    'compoundReturn' => $data
];
```
2. Add test data into the "Input Data JSON" field
```json
{"principal":1000,
"interest":3.9,
"time":2}
```
3. Press the "Execute" button

**Result:**
![image](https://user-images.githubusercontent.com/28575916/52598890-fca99180-2e0b-11e9-8c55-0f2d3bd2cd7b.png)

**Expected:**
The results of the script fill the full length of the content DIV.

**Comment by velkymx** [comment]
This is fixed
