### ISSUE TITLE
Can't hide File Upload / Download

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1591]
The File Download control in Screens Builder cannot be referenced in "Visibility Rules" expressions in other controls.

**Comment by marcoAntonioNina** [comment]
The component loading and download file works correctly with the Visibility Rule.

example.  import the process and enter the word test in text control, in preview or in case of execution.
[test_upload_download_file.bpm4.zip](https://github.com/ProcessMaker/bpm/files/3019720/test_upload_download_file.bpm4.zip)

**Comment by velkymx** [comment]
File Uploader works, but the downloader does not.
