### ISSUE TITLE
Change Timer Select 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1618]
Currently when setting a delay for the timer event I can set the timer for day / week / month / year. Please change it to hour / day / month. Values should be stored in minutes.

<img width="288" alt="Screenshot 2019-04-01 13 10 00" src="https://user-images.githubusercontent.com/535300/55356684-2b44ff80-5480-11e9-87af-479bc7495d0c.png">

**Comment by caleeli** [comment]
@marcoAntonioNina This is the ISO8601 for:
- 1 hour: PT1H
- 1 day: P1D
- 1 month: P1M
