### ISSUE TITLE
API Docs Not Loading

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1619]
When I go to the api docs I get the HTML page loading then a bunch of 404s for assets. What commands are we not running to generate?

<img width="564" alt="Screenshot 2019-04-02 08 27 17" src="https://user-images.githubusercontent.com/535300/55415046-2edc9300-5521-11e9-95af-e8dd13460edd.png">

**Comment by velkymx** [comment]
@nolanpro what are we missing?

**Comment by Kookster310** [comment]
Hi @velkymx 
I found the issue with had to deal with nginx and our browser caching configuration.
Someone had the same issue as us here: https://github.com/DarkaOnLine/L5-Swagger/issues/75
Once I removed the browser caching section, the docs started generating properly.

I believe we can go ahead and close this issue out.

**Comment by Kookster310** [comment]
In order to keep the browser caching working on the nginx side, we added the following:
try_files $uri /index.php
The API documentation is loading properly and the nginx caching config is still in tact.
