### ISSUE TITLE
Update Branding

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1629]
Update everywhere where it says ProcessMaker 4 to become ProcessMaker Spark.

- [x] Update Composer - Ciev is in the process of updating packagist
- [x] Update NPM - Ciev is in the process of updating npmjs
- [x] Update all references to "vue-form-builder" to spark-screen-builder
- [x] Update package.json
- [x] Update installer
- [x] Console commands
- [x] Homestead.yaml
- [x] Update About page
- [x] Update Page Titles
- [x] CircleCI
- [x] Develop URL https://develop.bpm4.qa.processmaker.net => https://develop.spark.qa.processmaker.net - Dan is working on this now
- [x] spark-connector-send-email https://github.com/ProcessMaker/spark-connector-send-email/pull/14
- [x] spark-sdk-lua, spark-sdk-php, spark-sdk-node
- [x] spark-docker-executor-php, spark-docker-executor-lua, spark-docker-executor-node

**Comment by nolanpro** [comment]
I let Ciev know in slack to update packagist and npmjs. These are all the updated repos:
```
spark-connector-send-email
spark-package-auth-saml
spark-package-oauth
spark-package-salesforce
spark-package-skeleton
spark-package-translations
spark-package-scheduling
spark-package-auth-saml
spark-package-collections
spark-sdk-lua
spark-sdk-php
spark-sdk-node
spark-docker-executor-php
spark-docker-executor-lua
spark-docker-executor-node
```
