### ISSUE TITLE
Translation Packages in Packagist

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1643]
@Cievoloth we need to add the translations to packagist for installation via the package installer.

**Comment by velkymx** [comment]
@Cievoloth this is ready to be on packagist. Let me know what you need from our team to make this happen.

**Comment by Cievoloth** [comment]
@velkymx  How do you normally install them? where are they placed? is somethig that ca be done with a composer require?

**Comment by Cievoloth** [comment]
installation can now be done via private packagist 

composer require processmaker/spark-package-translations
