### ISSUE TITLE
Record List Cannot be Hidden

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1644]
Visibility rules are not being respected for hiding and showing the Records List in the Form Builder preview.

**Comment by nolanpro** [comment]
Wasn't able to reproduce. Could you try it again? Might have been fixed in recent release.
![Kapture 2019-05-06 at 13 16 36](https://user-images.githubusercontent.com/2546850/57242387-5da6c700-7001-11e9-957f-ace4a99ac7a5.gif)
