### ISSUE TITLE
Non-Standard Modal

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1647]
When editing the page name in the Screen Builder, you see a non-standard modal. 

<img width="692" alt="Screenshot 2019-04-12 11 02 28" src="https://user-images.githubusercontent.com/535300/56056965-872a4680-5d12-11e9-8882-f19df3409ace.png">

**Comment by milaendo** [comment]
https://github.com/ProcessMaker/spark-screen-builder/pull/143
