### ISSUE TITLE
Screen Names with Ampersand Showing Code

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1648]
<img width="272" alt="Screenshot 2019-04-12 11 04 16" src="https://user-images.githubusercontent.com/535300/56057051-bfca2000-5d12-11e9-9bf8-96e2a53ac8e0.png">

Furthermore, if you change the Screen name from one with said ampersand to "and" you get double coded ampersands. Ryan says, "Very strange behavior".

<img width="412" alt="Screenshot 2019-04-12 11 05 09" src="https://user-images.githubusercontent.com/535300/56057133-f142eb80-5d12-11e9-97a7-2a99e842f373.png">

**Comment by PMQABen** [comment]
This also occurs in:
* Environment Variables (description)
* Scripts (name)
* Categories (name)
* Processes (name and description)
* Users (first name, last name, phone, address, city, postal code)
