### ISSUE TITLE
Add Active Directory (LDAP) account login

### ISSUE THREAD

**Issue by DiMiGi** [ProcessMaker/spark#1666]
In order to use accounts in a company is always a great idea to have a single account, normally Active Directory (AD) is used.

I already implemented this on [my forked project](https://github.com/DiMiGi/spark) and I made it on [this branch](https://github.com/DiMiGi/spark/tree/feature/LDAP).

PD: The develop branch has also issue #1633 implemented and has [its own branch](https://github.com/DiMiGi/spark/tree/feature/1633).

Feel free to use it as you want.

Greetings and happy coding!

**Comment by tdondich** [comment]
Hi @DiMiGi , we actually implement this and more features in an enterprise package.  the intent is that you do not put this in the core product but instead add an installable package to provide support for other authentication mechanisms.  If you want to open source such a package, that would be awesome.  I'm going to close this in favor of the approach being that different authentication support should be as an installable package.

**Comment by DiMiGi** [comment]
@tdonich Should I delete the ldap implementation from the forked Repo? As you have that in an enterprise package I think that shouldn't be in a public repo, right?
