### ISSUE TITLE
Remove Canceled Request from My Requests

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1682]
Canceled requests should show in the "Completed" requests screen only.

![Screenshot 2019-04-18 11 31 51](https://user-images.githubusercontent.com/535300/56382994-922b1e00-61cd-11e9-8339-47e82a836694.png)

**Comment by danloa** [comment]
@velkymx Do canceled requests should appear in the "all" tab? In my opinion they should be visible there too.
