### ISSUE TITLE
Pre-Scale Avatar

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1688]
When a user uploads a very large image to the avatar window it doesn't scale the image by default. We need to scale it to fit the modal and then, using the slider, allow the user to zoom in. 

Steps to Reproduce:

Edit a user portrait

import a big image

select the end of it

Current Behavior:
The user needs to swipe down until the end is reached

Expected Behavior:
The user can jump from one point to another

Potential Fix:
Implement a lateral and vertical slider

**Comment by PMQABen** [comment]
Correct me if I'm wrong, but this package is working exactly as intended. Even Facebook's avatar editor works like this.
