### ISSUE TITLE
Assign User to Multiple Groups

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1689]
Steps to Reproduce:

Go to a users profile > groups

Click in add user to group

Select a group

Current Behavior:
Selection dropdown closes after every selection

Expected Behavior:
The user can select any necessary groups before closing the dropdown

Potential Fix:
Either change the dropdown for another more appropriate object or change the dropdown so it won't close after one selection

**Comment by milaendo** [comment]
![Kapture 2019-04-18 at 15 03 09](https://user-images.githubusercontent.com/29641725/56394165-46876d00-61eb-11e9-9fc0-54375c5dd3bd.gif)
![Kapture 2019-04-18 at 15 01 07](https://user-images.githubusercontent.com/29641725/56394166-46876d00-61eb-11e9-8809-f40ef2a52d05.gif)

The first gif is from the documentation of that lib, from what I understand this is how this lib behaves. I believe this is also how the multiselect behaves system wide. Do we want to use a different lib, or override the behavior everywhere or just here?

**Comment by milaendo** [comment]
The conversation in slack about this ticket is that this is reporting that you cannot add multiple groups to a user. I was not able to reproduce this problem.
