### ISSUE TITLE
Timezone Formatting

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1691]
Steps to Reproduce:

go to admin > users

edit a user

change its timezone

Current Behavior:
Continent appears first in the name list making it hard to select a country by typing its name

Expected Behavior:
Country appears first together with the number relative to the timezone

Potential Fix:
Change the order Continent/Country to City/Country +number
‘La Paz/Bolivia +4’

**Comment by PMQABen** [comment]
https://en.wikipedia.org/wiki/Tz_database

Continent/Country is how the tz datbase is formatted. Changing this to City/Country +Num would potentially require us to write custom code to cover 561 different timezones.

**Comment by milaendo** [comment]
There are a few new ticket opened with this format of 'Expected Behavior' are these referencing PRD's?
