### ISSUE TITLE
Profile Password Validation Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1692]
I put in the password "admin" initially and it failed validation. When I went and changed it to "12345678" eight characters long, I still get the error and cannot save it.

![Screenshot 2019-04-18 14 53 01](https://user-images.githubusercontent.com/535300/56393563-ada42200-61e9-11e9-9f63-2f63c43dcea9.png)

**Comment by ryancooley** [comment]
Can't reproduce.

**Comment by PMQABen** [comment]
Same. What branch was this on?

**Comment by danloa** [comment]
@velkymx  Is working correctly in the current develop branch.
