### ISSUE TITLE
Multiselect Missing in Inspector

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1696]
What happened to the fancy vue-multiselect?

![Screenshot 2019-04-19 08 43 52](https://user-images.githubusercontent.com/535300/56431629-4df85600-627f-11e9-8343-022bb71dde13.png)

**Comment by milaendo** [comment]
I believe we only ever implemented this in the screen builder, but I could be totally wrong.

**Comment by velkymx** [comment]
I dont think so. Either way, you should be able to multi-select users and groups for assignment.

**Comment by marcoAntonioNina** [comment]
The multiselect is enabled on the ticket https://github.com/ProcessMaker/spark/issues/1668
