### ISSUE TITLE
No End Event Screen Showing Wrong Screen

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1698]
This happens intermittently, but we can see it when no screen is assigned to the end event. 

![image](https://user-images.githubusercontent.com/535300/56431865-32da1600-6280-11e9-8840-aeb56f96ab29.png)

**Comment by caleeli** [comment]
@velkymx could you share the process used to replicate the issue?

**Comment by velkymx** [comment]
I don't have a process that causes this. Let's confirm that a process without a configured end event works properly. @PMQABen can you reproduce this?

**Comment by PMQABen** [comment]
I got it to happen once on develop.spark, but further attempts to make it reproduce at 100% on my local VM has been fruitless.

**Comment by caleeli** [comment]
Okey I will add a validation to check if the screen exists, if not it will show an error `missing screen` in the modeler.

**Comment by caleeli** [comment]
![image](https://user-images.githubusercontent.com/8028650/57465833-6b508c80-724d-11e9-9ecd-d42dcf60c356.png)
