### ISSUE TITLE
My Tasks Showing Other Tasks

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1706]
When I am logged on as "LC", why am I seeing a Task assigned to a different user? These should only be MY Tasks.

![image](https://user-images.githubusercontent.com/535300/56510606-24d60080-64df-11e9-816d-d3ee1d48bc3c.png)

**Comment by velkymx** [comment]
@lcriscuolo adding you to the issue

**Comment by milaendo** [comment]
do we know what kind of permissions this user has? @velkymx

**Comment by lcriscuolo** [comment]
@milaendo , this user has the "Make this user a Super Admin" permission.

**Comment by ryancooley** [comment]
@velkymx Recommend we hold on this until search refactor is merged as that will very much impact this ticket.

**Comment by milaendo** [comment]
@velkymx I believe that the merge of the search refactor has fixed this issue.

**Comment by nolanpro** [comment]
Just tested it and i'm not seeing it issue so I guess it was fixed.

With this process:
![image](https://user-images.githubusercontent.com/2546850/57740284-d940ed80-766b-11e9-8fcd-0e13a4002871.png)

Users were not able to see each other's tasks:
![image](https://user-images.githubusercontent.com/2546850/57740313-09888c00-766c-11e9-9d0e-eeaa9587f2a6.png)
