### ISSUE TITLE
Saving Screen not showing Alert

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1711]
When you save a screen you should see an alert that shows that the save was successful.

**Comment by milaendo** [comment]
I was not able to reproduce this, in both display and form screens I was shown the alert.
![Screen Shot 2019-04-22 at 9 59 53 AM](https://user-images.githubusercontent.com/29641725/56512857-72ee0280-64e5-11e9-95e7-348188b6425f.png)

![Screen Shot 2019-04-22 at 9 59 17 AM](https://user-images.githubusercontent.com/29641725/56512836-649fe680-64e5-11e9-84f0-916d6dd41afe.png)

**Comment by velkymx** [comment]
Hmm... might by my vagrant taking a long time to respond...
