### ISSUE TITLE
Add Script Validation Not Showing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1740]
![Screenshot 2019-04-23 11 32 26](https://user-images.githubusercontent.com/535300/56606631-866b9d00-65bb-11e9-9ac5-c5d5c353c4d6.png)

Not all required fields are highlighting when they fail.

**Comment by milaendo** [comment]
![Screen Shot 2019-04-23 at 2 57 20 PM](https://user-images.githubusercontent.com/29641725/56618650-1cadbc00-65d8-11e9-8c0a-ac873a7c8bef.png)

the only field that doesnt seem to have validation is the "run as". I was looking through vue-multiselects docs and it seems like they wont support bootstraps validation classes https://github.com/shentao/vue-multiselect/issues/718. Any idea for a work around @velkymx

**Comment by velkymx** [comment]
@milaendo check out https://vuelidate.netlify.com/#getting-started

**Comment by milaendo** [comment]
@velkymx This library is great, however it will be a big undertaking. I recommend we revisit after release
