### ISSUE TITLE
No visual confirmation of duplicated screen

### ISSUE THREAD

**Issue by ryancooley** [ProcessMaker/spark#1751]
When duplicating a screen, there is no visual confirmation that it has been duplicated. The modal does not disappear. There is no alert. However, an XHR request is sent and subsequently clicking save displays an error that the name has already been taken (as it has).

![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/867714/56769941-8ad4b900-6767-11e9-9a60-17feb1f8a794.gif)

**Comment by milaendo** [comment]
@ryancooley any chance you didnt have run watch going?

![Kapture 2019-04-25 at 15 52 04](https://user-images.githubusercontent.com/29641725/56773281-531f3e80-6772-11e9-84f4-933d5c7bbda8.gif)
