### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by milaendo** [ProcessMaker/spark#1757]
![Screen Shot 2019-04-25 at 9 20 48 AM](https://user-images.githubusercontent.com/29641725/56826178-62ed6000-6810-11e9-9996-459e1632a0db.png)

**Comment by danloa** [comment]
@milaendo  I can't reproduce the problem in my environment, is there a specific page where the problem happens?

**Comment by milaendo** [comment]
@danloa I think I may have found a place where this happens consistently. Possibly related to  https://github.com/ProcessMaker/spark/issues/1751

![Kapture 2019-05-03 at 11 27 37](https://user-images.githubusercontent.com/29641725/57162683-cee93e80-6da3-11e9-87e9-117ce2b372f3.gif)
