### ISSUE TITLE
Import Process on New Process Modal

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1759]
Merge the import dialog and the new process modal. It used to be there.

![upload-bpmn](https://user-images.githubusercontent.com/535300/56830481-4efb2b80-681b-11e9-9b26-3a57c71bfb54.png)

**Comment by milaendo** [comment]
![Screen Shot 2019-05-14 at 10 35 39 AM](https://user-images.githubusercontent.com/29641725/57719191-112c3e80-7634-11e9-91a0-c5065b08a40d.png)
