### ISSUE TITLE
Fix issues week19

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/spark#1814]
Assignment rules are not refreshed in the inspector after changing the selected task
![assignbyexpressions](https://user-images.githubusercontent.com/8028650/57539606-dadf7e00-7318-11e9-9a24-fcc4bc4c7dae.gif)

**Comment by caleeli** [comment]
2 requests:

- 1 in progress
- 1 cancelled
![image](https://user-images.githubusercontent.com/8028650/57539747-2b56db80-7319-11e9-9864-1e5f27dd15ca.png)

**Comment by marcoAntonioNina** [comment]
selected value remains in another start event component
![startPermission](https://user-images.githubusercontent.com/1747025/57541588-5d6a3c80-731d-11e9-9895-bc7da154b1f8.gif)
