### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/spark#1823]
These need to be wrapped in a translator `__(...) or $t(...)` and/or added to the en.json and/or sent to smartling and es.json/fr.json updated in the translations package

- [x] /requests - Status in request list showing completed/error/in progress
- [x] /requests - advanced search - processes/statuses/participants placeholders
- [x] /requests - Loading spinner jumbotron - "Loading. Please wait while your content is loaded"
- [x] /requests/{id} - "The System has completed the task"...
- [x] /taks/{id} completed tab. Vuetable with no results - "No Data Available" - Weird, it IS translated in other vuetables like when /admin/users is loading
- [x] /modeler/{id} - All BPMN elements on the left
- [x] /modeler/{id} - Undo/Redo/Reset/Upload XML buttons
- [x] /modeler/{id} - Default inspector (click in an empty area) Identifier, The id field should be unique across..., The Name of the Process
- [x] Modeler - Pretty much all the inspector name/helpers/placeholders for all the elements 🤦‍♂ 
- [x] ~Modeler - Default node names like "New Script Task"~ Needs to be handled in the modeler 
- [x] Modeler - start permission drop down - "Select..."
- [x] Modeler - user and group multiselect - "Type here to search" placeholder
- [x] Modeler - Screen multiselect (end event, others) - "Type here to search" placeholder
- [x] Modeler - Script Task - configuration expanded monaco editor - Close button
- [x] Notifications toolbar bell - "No Notifications Found"
- [x] Screen builder - Clear Color Selection, add screen, undo, redo, Rich Text, calcs, Element Background color
- [x] admin/users - active/inactive in listing and create modal
- [x] admin/users/{id}/edit - remove user from group "p Are you sure you want to delete"
- [x] /screens - create and list - form types

**Comment by PMQABen** [comment]
- [ ] `/admin/users/{id}/edit` - deleting API token
![image](https://user-images.githubusercontent.com/28575916/57952378-db8c8d00-78a1-11e9-81fd-a751197f224a.png)
- [ ] `/admin/users/{id}/edit` - Auth Clients permissions
![image](https://user-images.githubusercontent.com/28575916/57954031-a5054100-78a6-11e9-9d41-cc89242f9868.png)

**Comment by milaendo** [comment]
@PMQABen It seems that smartling translated scripts as "scripts", perhaps there is not an appropriate term for translating that?

**Comment by PMQABen** [comment]
That could be what happened, we'd need to hit up Smartling to verify. :D

**Comment by milaendo** [comment]
When this ticket is complete we will then need to send the update en file to smartling and then update the translations package with update es and fr files.
