### ISSUE TITLE
Script Output Test Failing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1868]
Tests\Feature\Api\ScriptsTest::testPreviewScript
ErrorException: Undefined index: output

/home/vagrant/processmaker/tests/Feature/Api/ScriptsTest.php:343

`343 return $response['output'] === ['response' => 1];`

**Comment by caleeli** [comment]
It is working in the current develop branch (7dfbb11e5a68d892f6ebf9898618559fdae3fc0b)

https://circleci.com/gh/ProcessMaker/spark/7423?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

![image](https://user-images.githubusercontent.com/8028650/58330000-ec8a5080-7e03-11e9-9b60-bb878c95de9d.png)

Also tested several times locally.
![image](https://user-images.githubusercontent.com/8028650/58330046-07f55b80-7e04-11e9-8b81-3f2f014b8721.png)
