### ISSUE TITLE
Packages List 500

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1905]
Install any package
Go to /admin/spark-packages

API Call fails

/api/1.0/package/packages/fetch?page=1&per_page=10&filter=&order_by=name&order_direction=asc:1 

Failed to load resource: the server responded with a status of 500 ()

TODO: Remove this route. There shouldn't be a packages page or sidebar item.

**Comment by danloa** [comment]
Resolves #500

This issue is resolved modifying the spark-packages project. A ticket and a PR was created in its repository:
Issue: https://github.com/ProcessMaker/spark-packages/issues/7
PR: https://github.com/ProcessMaker/spark-packages/pull/8
