### ISSUE TITLE
Notification Menu Click

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1961]
I also noticed that since 5.1, when you click on a notification you’re not taken to the task directly, but to the request. I think it was best as before, straight to the form, less clicks.

**Comment by caleeli** [comment]
In the current version of develop, the notification it is opening the Task.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/8028650/59355916-e2b68780-8cf5-11e9-8394-81aef83fbc42.gif)

**Comment by velkymx** [comment]
This is fixed
